AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/EndOfLine:
  EnforcedStyle: lf
  
Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/ArgumentAlignment:
  Enabled: false
  
Layout/LineLength:
  Max: 170
